
BLENDER="C:\Program Files\Blender Foundation\Blender 4.5\blender.exe"
DIST=../dist

all : \
    $(DIST)/concert.pnct \
    $(DIST)/concert.scene \

$(DIST)/concert.scene : concert.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "concert.blend:Main" "$(DIST)/concert.scene"

$(DIST)/concert.pnct : concert.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "concert.blend:Main" "$(DIST)/concert.pnct" 
